# ###### UNICAMENTE PARA LA APP


# desde la imagen basada, 
#(alpine: imagen basica de linux)
FROM node:20.15.1-alpine3.20

# Set working directory
RUN mkdir -p /var/www/pokedex
WORKDIR /var/www/pokedex

# Copiar el directorio y su contenido
# En copy el ultimo es el path de destino
COPY . ./var/www/pokedex
COPY package.json tsconfig.json tsconfig.build.json /var/www/pokedex/
RUN yarn install --prod
RUN yarn build


# Dar permiso para ejecutar la applicación
# crear usuario para las imagenes
RUN adduser --disabled-password pokeuser
# damos acceso unicamente a ese usuario a la carpeta
RUN chown -R pokeuser:pokeuser /var/www/pokedex
# cambio a ese usuario pokeuser
USER pokeuser

# Limpiar el caché
RUN yarn cache clean --force

EXPOSE 3000

CMD [ "yarn","start:dev" ]